apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "decision-engine.fullname" . }}-config
  labels:
    {{- include "decision-engine.labels" . | nindent 4 }}
data:
  development.toml: |-
    {{ .Files.Get "../configs/development.toml" | nindent 4 }}